### ISSUE TITLE
dockerfile install error，help？

### ISSUE THREAD

**Issue by hzy729** [Linaro/pkg-lava-server#16]
RUN bash /build-lava lava-dispatcher 2018.2 2018.2-1
bash /build-lava lava-server 2018.2 2018.2-1
WARNING: broken setuptools tarball - Debian bug #786977

Setting up lava-lxc-mocker (2018.2-1-1) ...
dpkg: dependency problems prevent configuration of lava-dispatcher:
 lava-dispatcher depends on python3-guestfs (>= 1.32.7); however:
  Package python3-guestfs is not installed.
 lava-dispatcher depends on python3-configobj; however:
  Package python3-configobj is not installed.
 lava-dispatcher depends on python3-netifaces (>= 0.10.0); however:
  Package python3-netifaces is not installed.
 lava-dispatcher depends on python3-nose; however:
  Package python3-nose is not installed.
 lava-dispatcher depends on python3-pexpect (>= 4.2); however:
  Package python3-pexpect is not installed.
 lava-dispatcher depends on python3-pyudev (>= 0.21); however:
  Package python3-pyudev is not installed.
 lava-dispatcher depends on python3-requests; however:
  Package python3-requests is not installed.
 lava-dispatcher depends on python3-serial; however:
  Package python3-serial is not installed.
 lava-dispatcher depends on python3-setproctitle (>= 1.1.8); however:
  Package python3-setproctitle is not installed.
 lava-dispatcher depends on python3-yaml; however:
  Package python3-yaml is not installed.
 lava-dispatcher depends on python3-zmq; however:
  Package python3-zmq is not installed.

dpkg: error processing package lava-dispatcher (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 lava-dispatcher
The command '/bin/sh -c bash /build-lava lava-dispatcher 2018.2 2018.2-1' returned a non-zero code: 1

Dockerfile add package，error ：
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Setting up lava (2018.2-1-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
lava-master: unrecognized service
lava-slave: unrecognized service
lava-server: unrecognized service
Stopping lava-coordinator: lava-coordinato.

**Comment by hzy729** [comment]
When we try to install lava-docker as your official document says, we encounter some problems. Such as we lost pipeline-relevant  and bundle-relevant modules when we install as the default settings(version 2017.11). When we use lava-dispacher with 2018.2 ,pkg-lava-dispacher with 
2018.2-1, and lava-server with 2018 ,pkg-lava-server with 2018.2-1 ,we got  "WARNING: broken setuptools tarball - Debian bug #786977" ,more details you can see the past code above. And other mixed version with lava-* and 
pkg* version will just "returned a non-zero code: 1". Since we hope to install the latest version of lava-docker , wish you can help us find the right way!

**Comment by ghost** [comment]
Sorry, lava-docker is not an official part of the LAVA software and has not necessarily kept up with changes in how LAVA software is built. We are working on official LAVA docker images. In the meantime, lava-docker is based on older versions of LAVA software and some changes will be needed to the lava-docker scripts. Those scripts are not part of the lava-server or lava-dispatcher codebase and cannot be fixed by the LAVA software developers.

Please subscribe to and post to the lava-users mailing list, as described in our documentation.
https://staging.validation.linaro.org/static/docs/v2/support.html#mailing-lists

The first issue you describe is that LAVA is moving to Python3 support, you need to install those dependencies to be able to install the current master branch of LAVA software.

Please read the relevant announcements:
https://lists.linaro.org/pipermail/lava-announce/2018-January/000046.html

Also: https://lists.linaro.org/pipermail/lava-announce/2017-September/000037.html

Bundles are only for V1 and have been removed from 2018.2, as outlined in the announcement back in November. Pipeline was a temporary redirection of the V2 content until V1 was removed. The code which was in the pipeline directory has now moved up to the top level.

These are all standard issues which you need to handle if you choose to use the developer build tools. You should instead be using the LAVA repositories, as described in the documentation.

https://staging.validation.linaro.org/static/docs/v2/installing_on_debian.html#lava-repositories

**Comment by hzy729** [comment]
Use commands to upgrade to V2 2018.2 version
But the source code in /usr/lib/python2.7/dist-packages/ is inconsistent with the source code on github

**Comment by ghost** [comment]
What commands? The only command you should be using is:
$ /usr/share/lava-server/debian-dev-build.sh -p lava-server

Python2 support has been dropped in the master branch. The next release will be Python3 only.
https://lists.linaro.org/pipermail/lava-announce/2018-April/000050.html

**Comment by ghost** [comment]
And GitHub is **not** the canonical location of LAVA software, it is a mirror which gets updated intermittently. The location you need to be using is https://git.linaro.org/lava/lava-server.git/

**Comment by hzy729** [comment]
Thanks for guidance, we have solved the installation problem
